name: habiter_app
description: "A Flutter application for habit tracking."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  sqflite: ^2.3.0
  path: ^1.9.0
  sliding_up_panel: ^2.0.0+1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/db/habit.db
  uses-material-design: true

flutter_native_splash:
  color: "#7886c7"
  image: assets/icon/Habiter.png
  android_12:
    image: assets/icon/Habiter.png
    branding: assets/icon/Habiter_text.png
    branding_bottom_padding: 90
